name       : lvm2
version    : 2.03.22
release    : 24
source     :
    - http://mirrors.kernel.org/sourceware/lvm2/LVM2.2.03.22.tgz : 4c5a6923bd1ace7ce04474608a84937ce053ba91b1ace9f0b0017268e732dc7c
license    : GPL-3.0-or-later
component  : system.base
summary    : The LVM2 package is a package that manages logical partitions.
description: |
    The LVM2 package is a package that manages logical partitions. It allows spanning of file systems across multiple physical disks and disk partitions and provides for dynamic growing or shrinking of logical partitions.
builddeps  :
    - libaio-devel
    - thin-provisioning-tools
optimize   :
    - size
    - lto
environment: |
    # Build is heavily dependent on bashisms
    export CONFIG_SHELL=/bin/bash
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-cache-dirs.patch
    %configure --enable-cmdlib \
               --enable-dmeventd \
               --enable-lvmpolld \
               --enable-pkgconfig \
               --enable-readline \
               --enable-udev_rules \
               --enable-udev_sync \
               --with-default-dm-run-dir=/run \
               --with-default-locking-dir=/run/lock/lvm \
               --with-default-pid-dir=/run \
               --with-default-run-dir=/run/lvm \
               --with-libexecdir=/usr/lib64/lvm2 \
               --with-systemdsystemunitdir=/usr/lib/systemd/system \
               --with-thin=internal \
               --with-udev-prefix=/usr
build      : |
    %make
install    : |
    %make_install install_systemd_units install_tmpfiles_configuration

    # Stateless
    rm -v $installdir/etc/lvm/lvm.conf
    rm -v $installdir/etc/lvm/lvmlocal.conf
    rm -v $installdir/etc/lvm/profile/cache-mq.profile
    rm -v $installdir/etc/lvm/profile/cache-smq.profile
    rm -v $installdir/etc/lvm/profile/command_profile_template.profile
    rm -v $installdir/etc/lvm/profile/lvmdbusd.profile
    rm -v $installdir/etc/lvm/profile/metadata_profile_template.profile
    rm -v $installdir/etc/lvm/profile/thin-generic.profile
    rm -v $installdir/etc/lvm/profile/thin-performance.profile
    rm -v $installdir/etc/lvm/profile/vdo-small.profile
    rmdir $installdir/etc/lvm/profile
    rmdir $installdir/etc/lvm/
    rmdir $installdir/etc/
