name        : lvm2
version     : 2.02.136
release     : 8
source     :
    - ftp://sources.redhat.com/pub/lvm2/releases/LVM2.2.02.136.tgz : c6af90097d8f7cd851d38c4f57bb3ad7039cfa123f1e336dba957814a298bd8c
license     :
    - GPLv3+
summary     :  The LVM2 package is a package that manages logical partitions. It allows spanning of file systems across multiple physical disks and disk partitions and provides for dynamic growing or shrinking of logical partitions.
builddeps   :
    - systemd-devel
description : |
    The LVM2 package is a package that manages logical partitions. It allows spanning of file systems across multiple physical disks and disk partitions and provides for dynamic growing or shrinking of logical partitions.
setup      : |
    %configure --exec-prefix=      \
               --with-confdir=/etc \
               --enable-applib     \
               --enable-cmdlib     \
               --enable-pkgconfig  \
               --enable-dmeventd   \
               --enable-udev_sync \
               --enable-lvmetad \
               --with-systemdsystemunitdir=/usr/lib/systemd/system
build      : |
    %make
install    : |
    %make_install install_systemd_units install_tmpfiles_configuration
