name       : lvm2
version    : 2.02.168
release    : 18
source     :
    - ftp://sources.redhat.com/pub/lvm2/releases/LVM2.2.02.168.tgz : 23a3d1cddd41b3ef51812ebf83e9fa491f502fe74130d4263be327a91914660d
license    :
    - GPLv3+
summary    : The LVM2 package is a package that manages logical partitions. It allows spanning of file systems across multiple physical disks and disk partitions and provides for dynamic growing or shrinking
    of logical partitions.
builddeps  :
    - systemd-devel
component  : system.base
description: |
    The LVM2 package is a package that manages logical partitions. It allows spanning of file systems across multiple physical disks and disk partitions and provides for dynamic growing or shrinking of logical partitions.
setup      : |
    sed -i 's|use_lvmetad = 0|use_lvmetad = 1|' conf/example.conf.in
    %configure --exec-prefix=      \
               --with-confdir=/etc \
               --enable-applib     \
               --enable-cmdlib     \
               --enable-pkgconfig  \
               --enable-dmeventd   \
               --sbindir=/sbin     \
               --enable-udev_sync \
               --with-udevdir=%libdir%/udev/rules.d \
               --enable-udev_rules \
               --with-default-run-dir=/run/lvm  \
               --with-default-locking-dir=/run/lock/lvm \
               --enable-lvmpolld \
               --enable-lvm1_fallback \
               --enable-fsadm \
               --with-pool=internal \
               --enable-write_install \
               --enable-lvmetad \
               --with-systemdsystemunitdir=/usr/lib/systemd/system
build      : |
    %make
install    : |
    %make_install
    %make_install install_system_dirs install_systemd_units
    %make_install install_tmpfiles_configuration install_systemd_generators
    rm -rf $installdir/var/
    rm -rf $installdir/run
